config/routes.rb
Rails.application.routes.draw do

  devise_for :admins, class_name: "App::Admin", controllers: { sessions: 'admins/sessions'}
  devise_for :users, class_name: "App::User", controllers: { sessions: 'users/sessions'}
  
  root to: "site#index", as: :site_root
  
  # - - - - - - - - - - ROUTES FOR SITE - - - - - - - - - - 

  get 'unsubscribe', to: 'app/subscribers#unsubscribe', as: :unsubscribe
  post '/toogle_locale', to: 'site#toogle_locale', as: :toogle_locale
  post '/contact_forms', to: 'site#contact_forms', as: :contact_forms

  get '/:slug', to: 'app/prospects#new_by_slug'

  # - - - - - - - - - - ROUTES FOR APPLICATION - - - - - - - - - - 


  devise_scope :user do
    authenticated :user do
      root 'app/users#index', as: :user_authenticated_root
    end

    unauthenticated do
      namespace :app do
        root 'devise/sessions#new', as: :unauthenticated_root
      end
    end
  end

  devise_scope :admins do 
    authenticated :admin do
      root 'app/clients#index', as: :admin_authenticated_root
      
      # Exclusive routes in App namespace (just for admin)
      namespace :app do
        resources :admins, only: [:update]
        resources :clients do
          delete :destroy_attachment, on: :member
          get :search, on: :collection
          post :recalculate_periods, on: :collection
        end
        resources :subscribers, only: [:index]
        resources :updates 
      end
    end
  end

  # Commom routes in App namespace
  namespace :app do
    resources :role_vendors do
      get :search, on: :collection
    end
    resources :interactions do 
      get :search, on: :collection
    end

    resources :status_interactions do
      get :search, on: :collection
    end
    resources :contacts do 
      get :search, on: :collection
    end

    resources :classes, only: [:index] do
      get :search, on: :collection
    end 


    resources :negotiations, except: %i[new create destroy] do
      get :search, on: :collection
      get :filter, on: :collection
    end

    resources :status_negotiations do
      get :search, on: :collection
    end

    get :settings, to: 'settings#index'

    resources :companies do
      get :search, on: :collection
    end

    resources :calendars do
      get :search, on: :collection
      delete :destroy_confirm, on: :member
    end

    resources :courses do 
      get :search, on: :collection
      get :filter, on: :collection
    end
  
    resources :institutions do
        get :search, on: :collection
        delete :destroy_attachment, on: :member
    end
    
    resources :prospects do 
      get :search, on: :collection
    end
    resources :vendors do 
      get :search, on: :collection
    end

    resources :cities do 
      get :filter, on: :collection
      get :search, on: :collection
    end
    
    resources :users do
      get :search, on: :collection
    end
    resources :subscribers, only: [:create, :destroy]
    resources :updates, only: [:index, :show]
  end
  
end

app/models/app/city.rb
class App::City < ApplicationRecord
  belongs_to :client, class_name: 'App::Client'
  has_and_belongs_to_many :vendors, class_name: 'App::Vendor', join_table: 'app_cities_vendors'
  has_many :institutions, class_name: 'App::Institution'
  has_many :courses, class_name: 'App::Course', through: :institutions

  # Through Associations
  has_many :negotiations, through: :institutions
  has_many :courses, through: :institutions

  # Validations
  validates :name, :state,  presence: true
  validates_uniqueness_of :name, scope: :client_id
  
  # Scopes
  include App::Scopes

  scope :by_negotiation, ->(negotiation_ids) { joins(:negotiations).where(negotiations: {id: negotiation_ids}) }
  scope :by_course, ->(course_ids) { joins(:courses).where(courses: {id: course_ids}) }
  scope :by_uf, ->(uf) { where(state: uf) }
  scope :search, -> (search) { where("LOWER(UNACCENT(name)) LIKE LOWER(UNACCENT(:search))", search: "%#{search}%") }


  # Methods
  def has_dependency?
    self.institutions.any?
  end

  def name_and_uf
    "#{self.name} - #{self.state}"
  end


end

app/models/app/vendor.rb
class App::Vendor < ApplicationRecord
  belongs_to :client, class_name: 'App::Client'
  belongs_to :role, class_name: 'App::RoleVendor', optional: true

  has_and_belongs_to_many :cities, class_name: 'App::City', join_table: 'app_cities_vendors'
  has_one :user, class_name: 'App::User'
  has_many :prospects, class_name: 'App::Prospect'
  has_many :negotiations, class_name: 'App::Negotiation'


  # Validations
  validates :client_id, presence: true
  validates :name, presence: true, uniqueness: { scope: :client_id }
  validates :email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i}, allow_blank: true
  
  # Scopes
  include App::Scopes
  scope :search, -> (search) { where("LOWER(UNACCENT(name)) LIKE LOWER(UNACCENT(:search))", search: "%#{search}%") }
  
  scope :by_role, ->(role_id) do
    # return where(role_id: role_id) 
    if role_id.is_a?(App::Vendor)
      where(role_id: role_id)
    elsif role_id.include?('-1') # Se o array de role_id incluir uma string vazia
      where(role_id: [nil] + role_id.reject(&:empty?)) # Inclui nil e os outros ids não vazios
    else
      where(role_id: role_id.reject(&:empty?))
    end
  end
  
end

app/controllers/app/vendors_controller.rb
class App::VendorsController < ApplicationController
  
  before_action :authenticate_user_or_admin!
  before_action :check_client_id, only: %i[ show edit update destroy]  
  before_action :set_app_vendor, only: %i[ show edit update destroy ]
  before_action :set_content_for_form, only: %i[ new edit create update ]
  before_action :set_content_for_sidebar, only: %i[ index search ]
  
  # GET /app/vendors or /app/vendors.json
  def index
    collection = App::Vendor.by_client(get_client_id).order(:name)
    @pagy,  @app_vendors = set_pagy(collection)
  end

  # GET /app/vendors/1 or /app/vendors/1.json
  def show
  end

  # GET /app/vendors/new
  def new
    @app_vendor = App::Vendor.new(role_id: params[:role_id])
  end

  # GET /app/vendors/1/edit
  def edit
  end

  # POST /app/vendors or /app/vendors.json
  def create
    @app_vendor = App::Vendor.new(app_vendor_params)
    set_client_id(@app_vendor)

    if @app_vendor.save
      flash[:success] = t('views.app.general.flash.create_m', model: App::Vendor.model_name.human)
      redirect_to app_vendor_url(@app_vendor)
    else
      flash[:error] = 'deu ruim'
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /app/vendors/1 or /app/vendors/1.json
  def update
    if @app_vendor.update(app_vendor_params)
      flash[:success] = t('views.app.general.flash.update_m', model: App::Vendor.model_name.human)
      redirect_to app_vendor_url(@app_vendor)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /app/vendors/1 or /app/vendors/1.json
  def destroy
    @app_vendor.destroy
    flash[:success] = t('views.app.general.flash.destroy_m', model: App::Vendor.model_name.human)
    redirect_to app_vendors_url
  end

  
  #  GET /app/vendors/search?query=:query
  def search 

    collection = App::Vendor.by_client(get_client_id).order(:name)
    
    if %i[query role_ids].any? { |key| params[key].present? }
      collection = collection.search(params[:query]) if params[:query].present?
      collection = collection.by_role(params[:role_ids]) if params[:role_ids].present?
    else
      return redirect_to app_vendors_path 
    end
  
    @pagy,  @app_vendors = set_pagy(collection)
    
    render :index

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_app_vendor
      @app_vendor = App::Vendor.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def app_vendor_params
      params.require(:app_vendor).permit(:name, :phone, :email, :role_id, city_ids: [])
    end

    def set_content_for_form
      @cities = App::City.by_client(get_client_id).order(:state, :name)
      @roles = App::RoleVendor.by_client(get_client_id).where(active: true).order(:name)
    end

    def set_content_for_sidebar
      null_role = OpenStruct.new(id: -1, name: t('activerecord.blank_entries.role'))
      @roles = [null_role] + App::RoleVendor.by_client(get_client_id).order(:name)
    end
end

app/helpers/app/vendors_helper.rb
module App::VendorsHelper
end

app/views/app/vendors/_detail.html.erb
<div class="space-y-4">

  <div class="grid grid-cols-1 md:grid-cols-2 gap-4">

    <div class="">
      <p class=""><%= App::Vendor.human_attribute_name('name')%></p>
      <p class="detail-input"><%= app_vendor.name  %></p>
    </div>

    <div class="">
      <p class=""><%= App::Vendor.human_attribute_name('role')%></p>
      <p class="detail-input"><%= app_vendor.role.present? ? app_vendor.role.name : t('activerecord.blank_entries.role') %></p>
    </div>

    <div class="">
      <p class=""><%= App::Vendor.human_attribute_name('phone')%></p>
      <p class="detail-input"><%= app_vendor.phone.present? ? app_vendor.phone : t('activerecord.blank_entries.phone') %></p>
    </div>

    <div class="">
      <p class=""><%= App::Vendor.human_attribute_name('email')%></p>
      <p class="detail-input"><%= app_vendor.email.present? ? app_vendor.email : t('activerecord.blank_entries.email') %></p>
    </div>

  </div>

  <%# USERS TITLE %>
  <% if app_vendor.cities.present? %>
  <div class="">
    <p class="font-bold text-2xl"> <%= App::Vendor.human_attribute_name('city_ids') %> </p>
      <div class="mt-2 default-grid">
        <%= render app_vendor.cities %>
      </div>
  </div>
  <% end %>

</div>

app/views/app/vendors/_form.html.erb
<%= form_with(model: app_vendor, class: "contents") do |form| %>
  <% if app_vendor.errors.any? %>
    <% flash.now[:error] = app_vendor.errors.to_a%>
  <% end %>

  <div class="grid grid-cols-1 md:grid-cols-2 gap-4">

    <div class="">
      <%= form.label :name, class:'required' %>
      <%= form.text_field :name, class: "form-input", placeholder: t('activerecord.placeholders.app/vendor.name') %>
    </div>

    <div class="">
      <%= form.label :role_id, class:'' %>
      <div class="flex justify-between space-x-2 items-center ">
        <%= form.collection_select :role_id, @roles, :id, :name, {include_blank: t('activerecord.blank_entries.role')}, {class: "form-input"} %>
        <%= link_to new_app_role_vendor_path, class: "btn-primary flex-none mt-2 h-10 pt-2.5" do %>
          <%= icon('fa-solid','plus',class:'-mr-2 2xl:-mr-0 btn-icon') %>
          <span class="hidden 2xl:inline"><%= App::RoleVendor.model_name.human %></span>
        <% end %>
      </div>
    </div>


  <div class="">
    <%= form.label :phone %>
    <%= form.text_field :phone, class: "form-input", placeholder: t('activerecord.placeholders.app/vendor.phone') %>
  </div>

  <div class="">
    <%= form.label :email %>
    <%= form.text_field :email, class: "form-input", placeholder: t('activerecord.placeholders.app/vendor.email') %>
  </div>

</div>

<%# CITIES INPUT %>
<% if @cities.present? %>
  <div class="mt-4">
    <p class="font-bold text-2xl"> <%= App::Vendor.human_attribute_name('city_ids') %> </p>
    <div class="mt-2 bg-gray-100 dark:bg-gray-900 py-2 px-3 space-y-1 rounded-lg text-sm grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3">
      <%= form.collection_check_boxes  :city_ids, @cities, :id, :name_and_uf, include_hidden: true do |city| %>
        <div class="">
          <%= city.check_box(class: 'form-checkbox-simple dark:bg-gray-800 bg-gray-200 mr-1 ') %>
          <%= city.label class:'cursor-pointer text-sm' do %>
            <%= city.text %>
          <% end %>
        </div>
      <% end %>
    </div>
  <% end %>
</div>
<%# END OF CITIES %>

<div class="mt-4 inline-flex w-full justify-end">
  <%= form.submit class: "btn-primary" %>
</div>

<% end %>

app/views/app/vendors/_sidebar.html.erb
<div class="" data-controller='search reveal' data-reveal-hidden-class="hidden">
  <div class="detail-input text-xs text-center h-8 -mb-1" id="pagy_info">
    <%== pagy_info(@pagy, item_name: App::Vendor.model_name.human(count: @pagy.items)) %>
  </div>

  <%= form_with(url: search_app_vendors_path, method: :get,  class:'space-y-1') do |form| %>

    <%# SEACH INPUT %>
    <div class="relative" data-action='mouseenter->reveal#toggle mouseleave->reveal#toggle '>
      <div class="search-input-icon dark:hover:bg-blue-600" data-action="click->search#submit"><%= icon('fa-solid','search', class:'fa-sm ') %>  </div>
      <%= form.text_field :query, value:params[:query],  class:'search-input text-sm', placeholder: t('views.app.general.search'), data: {action: 'keydown.enter->search#submit'} %>
    </div>

    <div class="hidden  detail-input text-xs h-8 " data-reveal-target="item">
      <p class="text-center">
        <%= %i[ name  ].map{|attr| App::Vendor.human_attribute_name(attr)}.join(" | ")  %>
      </p>
    </div>
    <%# END OF SEARCH INPUT%>

    <%# VENDORS INPUT %>

    <% if @roles.count >1%>

      <div class="bg-gray-100 dark:bg-gray-900 py-2 px-3 space-y-1 rounded-lg text-sm">

        <%= button_tag t('views.app.general.select_all_m'), type: "button", class: "w-full bg-gray-200 dark:bg-gray-800 hover:bg-blue-600 hover:text-white dark:hover:bg-blue-600 p-1 rounded-lg text-sm", data: { action: "search#selectAll search#submit" } if @roles.any?%>

        <%= form.collection_check_boxes  :role_ids, @roles, :id, :name, include_hidden: false do |role| %>
          <div class="mt-0 flex justify-between items-center">
            <div class="truncate">
              <%= role.check_box(class: 'form-checkbox-simple dark:bg-gray-800 bg-gray-200 mr-1 ', checked: (params[:role_ids].present? && params[:role_ids].include?(role.value.to_s)), data: {action: 'change->search#submit'}) %>
              <%= role.label class:'cursor-pointer text-sm' do %>
                <%= role.text %>
              <% end %>
            </div>
            <%= icon('fa-solid', 'bolt', class:'p-1.5 bg-gray-200 dark:bg-gray-800 rounded-lg hover:text-blue-600 cursor-pointer', data: { action:" click->search#selectOnly click->search#submit"} )%>
          </div>
        <% end %>
      </div>

    <% end %>

    <%# END OF VENDORS %>

  <% end %>

</div>

app/views/app/vendors/_vendor.html.erb
<div id="<%= dom_id vendor %>" class='card group' data-aos='fade' data-controller="reveal" data-reveal-hidden-class="grid">

  <div class="card-header">

    <div class="card-header-info card-header-animate">
      <p class="overflow-scroll scrollbar-hide"><%= link_to vendor.name, app_vendor_path(vendor), class:'card-header-title' %></p>
      <p class="card-header-subtitle card-header-subtitle-animate"><%= vendor.role.present? ? vendor.role.name : t('activerecord.blank_entries.role') %></p>
    </div>

    <%= button_tag class:'card-header-btn', data: { action:"click->reveal#toggle" }  do %>
      <%= icon('fa-solid','bars', class:'fa-sm')%>
    <%end%>

  </div>

  <div data-reveal-target="item" class="card-popover w-24 " data-action="mouseleave->reveal#show">
    <%= link_to edit_app_vendor_path(vendor), class:'card-popover-btn-primary' do %>
      <%= icon('fa-solid', 'pen-to-square', class:'btn-icon') %>
      <p class=""> <%= t('views.app.general.edit')%></p>
    <%end%>
  </div>

</div>

app/views/app/vendors/_vendors.html.erb
<div class="default-grid">
  <%= render(@app_vendors) %>
</div>

app/views/app/vendors/edit.html.erb
<% content_for :ctas_secondary do %>
  <%= link_to app_vendors_path, class: "btn-secondary-gray flex-none" do %>
    <%= icon('fa-solid','arrow-left', class:'-mx-1')%>
  <%end%>

  <%= link_to app_vendor_path(@app_vendor), class: "btn-secondary flex-none" do %>
    <%= icon('fa-solid','arrow-up-right-from-square', class:'-mx-1')%>
  <%end%>
<% end %>

<% provide :head_title, "#{t('views.app.general.editing')} #{App::Vendor.model_name.human}" %>
<% provide :page_title, "#{t('views.app.general.editing')} #{App::Vendor.model_name.human}" %>
<% provide :entry_id, "#{@app_vendor.id}" %>

<% content_for :page_content do %>
  <%= render "form", app_vendor: @app_vendor %>
<%end%>

app/views/app/vendors/index.html.erb
<% content_for :ctas_primary do %>
  <%= link_to new_app_vendor_path, class: "btn-primary flex-none" do %>
    <%= icon('fa-solid','plus',class:'btn-icon') %>
    <%= App::Vendor.model_name.human %>
  <% end %>
<% end %>

<% provide :head_title, App::Vendor.model_name.human.pluralize %>
<% provide :page_title, App::Vendor.model_name.human.pluralize %>
<% provide :sidebar, render(partial: 'app/vendors/sidebar') %>

<% content_for :page_content do %>

  <%= render partial: 'vendors' %>

<%end%>

app/views/app/vendors/new.html.erb
<% content_for :ctas_secondary do %>
  <%= link_to app_vendors_path, class: "btn-secondary-gray flex-none" do %>
    <%= icon('fa-solid','arrow-left', class:'-mx-1')%>
  <%end%>
<% end %>

<% provide :page_title, "#{t('views.app.general.new')} #{App::Vendor.model_name.human}" %>

<% content_for :page_content do %>
  <%= render "form", app_vendor: @app_vendor %>
<%end%>

app/views/app/vendors/show.html.erb
<% content_for :ctas_secondary do %>
  <%= link_to app_vendors_path, class: "btn-secondary-gray flex-none" do %>
    <%= icon('fa-solid','arrow-left', class:'-mx-1')%>
  <%end%>

  <%= link_to edit_app_vendor_path(@app_vendor), class: "btn-secondary flex-none" do %>
    <%= icon('fa-solid','pen-to-square', class:'-mx-1')%>
  <%end%>

  <%= button_to app_vendor_path(@app_vendor), method: :delete, data: { turbo: false },onclick: "return confirm('#{t('views.app.general.delete_confirm')}')",class: "btn-delete flex-none" do %>
    <%= icon('fa-solid','trash-can', class:'-mx-1')%>
  <%end%>
<% end %>

<% content_for :ctas_primary do %>
  <%= link_to search_app_prospects_path(vendor_ids: @app_vendor.id, status: 'prospected'), class: "btn-primary flex-none" do %>
    <%= icon('fa-solid','receipt',class:'btn-icon') %>
    <%= App::Prospect.model_name.human(count:2) %>
  <% end %>

  <%= link_to search_app_interactions_path(vendor_ids: @app_vendor.id), class: "btn-primary flex-none" do %>
    <%= icon('fa-solid','list',class:'btn-icon') %>
    <%= App::Interaction.model_name.human(count:2) %>
  <% end %>

  <%= link_to search_app_negotiations_path(vendor_ids: [@app_vendor.id]), class: "btn-primary flex-none" do %>
    <%= icon('fa-solid','table-columns',class:'btn-icon') %>
    <%= App::Interaction.model_name.human(count:2) %>
  <% end %>

<% end %>

<% provide :head_title, "#{t('views.app.general.showing')} #{App::Vendor.model_name.human} " %>
<% provide :page_title, "#{t('views.app.general.showing')} #{App::Vendor.model_name.human} " %>
<% provide :entry_id, "#{@app_vendor.id}" %>

<% content_for :page_content do %>
  <%= render "detail", app_vendor: @app_vendor %>
<%end%>