config/routes.rb
Rails.application.routes.draw do

  devise_for :admins, class_name: "App::Admin", controllers: { sessions: 'admins/sessions'}
  devise_for :users, class_name: "App::User", controllers: { sessions: 'users/sessions'}
  
  root to: "site#index", as: :site_root
  
  # - - - - - - - - - - ROUTES FOR SITE - - - - - - - - - - 

  get 'unsubscribe', to: 'app/subscribers#unsubscribe', as: :unsubscribe
  post '/toogle_locale', to: 'site#toogle_locale', as: :toogle_locale
  post '/contact_forms', to: 'site#contact_forms', as: :contact_forms

  get '/:slug', to: 'app/prospects#new_by_slug'

  # - - - - - - - - - - ROUTES FOR APPLICATION - - - - - - - - - - 


  devise_scope :user do
    authenticated :user do
      root 'app/users#index', as: :user_authenticated_root
    end

    unauthenticated do
      namespace :app do
        root 'devise/sessions#new', as: :unauthenticated_root
      end
    end
  end

  devise_scope :admins do 
    authenticated :admin do
      root 'app/clients#index', as: :admin_authenticated_root
      
      # Exclusive routes in App namespace (just for admin)
      namespace :app do
        resources :admins, only: [:update]
        resources :clients do
          delete :destroy_attachment, on: :member
          get :search, on: :collection
          post :recalculate_periods, on: :collection
        end
        resources :subscribers, only: [:index]
        resources :updates 
      end
    end
  end

  # Commom routes in App namespace
  namespace :app do
    resources :role_vendors do
      get :search, on: :collection
    end
    resources :interactions do 
      get :search, on: :collection
    end

    resources :status_interactions do
      get :search, on: :collection
    end
    resources :contacts do 
      get :search, on: :collection
    end

    resources :classes, only: [:index] do
      get :search, on: :collection
    end 


    resources :negotiations, except: %i[new create destroy] do
      get :search, on: :collection
      get :filter, on: :collection
    end

    resources :status_negotiations do
      get :search, on: :collection
    end

    get :settings, to: 'settings#index'

    resources :companies do
      get :search, on: :collection
    end

    resources :calendars do
      get :search, on: :collection
      delete :destroy_confirm, on: :member
    end

    resources :courses do 
      get :search, on: :collection
      get :filter, on: :collection
    end
  
    resources :institutions do
        get :search, on: :collection
        delete :destroy_attachment, on: :member
    end
    
    resources :prospects do 
      get :search, on: :collection
    end
    resources :vendors do 
      get :search, on: :collection
    end

    resources :cities do 
      get :filter, on: :collection
      get :search, on: :collection
    end
    
    resources :users do
      get :search, on: :collection
    end
    resources :subscribers, only: [:create, :destroy]
    resources :updates, only: [:index, :show]
  end
  
end

app/controllers/app/interactions_controller.rb
class App::InteractionsController < ApplicationController
  before_action :set_app_interaction, only: %i[ show edit update destroy ]
  before_action :set_content_for_form, only: %i[ new create edit update ]
  before_action :set_content_for_sidebar, only: %i[ index search ]

  # GET /app/interactions or /app/interactions.json
  def index
    if current_access_is_user? && get_current_access.vendor 
      collection = App::Interaction.by_client(get_client_id).by_vendor(get_current_access.vendor_id).includes(:vendor, :status, negotiation: { course: {institution: :city }}).order(created_at: :desc ) 
    else
      collection = App::Interaction.none 
    end
    @pagy,  @app_interactions = pagy(collection)
    set_variables_for_sidebar(collection)

    @collection_src_url = 'app_interactions_url'

    respond_to do |format|
      format.html  
      format.turbo_stream 
    end
    
  end

  # GET /app/interactions/1 or /app/interactions/1.json
  def show
  end

  # GET /app/interactions/new
  def new
    @app_interaction = App::Interaction.new(negotiation_id: params[:negotiation_id], status_id: params[:status_id])
  end

  # GET /app/interactions/1/edit
  def edit
  end

  # POST /app/interactions or /app/interactions.json
  def create
    @app_interaction = App::Interaction.new(app_interaction_params)
    set_client_id(@app_interaction)

    if @app_interaction.save
      flash[:success] = t('views.app.general.flash.create_f', model: App::Interaction.model_name.human)
      redirect_to app_interaction_url(@app_interaction)
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /app/interactions/1 or /app/interactions/1.json
  def update
    if @app_interaction.update(app_interaction_params)
      flash[:success] = t('views.app.general.flash.update_f', model: App::Interaction.model_name.human)
      redirect_to app_interaction_url(@app_interaction)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /app/interactions/1 or /app/interactions/1.json
  def destroy
    @app_interaction.destroy
    flash[:success] = t('views.app.general.flash.destroy_f', model: App::Interaction.model_name.human)
    redirect_to app_interactions_url
  end

  #  GET /app/interactions/search?query=:query&status_ids=:status&vendors_ids=:vendors
  def search 
    collection = App::Interaction.by_client(get_client_id).includes(:vendor, :status, negotiation: { course: {institution: :city }})
    

    if params[:query].present? || params[:status_ids].present? || params[:vendor_ids].present?
      collection = collection.search(params[:query]) if params[:query].present?
      collection = collection.by_status_interaction(params[:status_ids]) if params[:status_ids].present?
      collection = collection.by_vendor(params[:vendor_ids]) if params[:vendor_ids].present?
    else
      return redirect_to app_interactions_path
    end

    @pagy,  @app_interactions = pagy(collection.order(created_at: :desc))
    set_variables_for_sidebar(collection)
    @collection_src_url = 'search_app_interactions_path'
    
    
    respond_to do |format|
      format.html do
        render  "app/interactions/index"
      end
      format.turbo_stream do
        render  "app/interactions/index",
                locals: { collection: @app_interactions, collection_name: "interactions"}
      end
    end


  end



  private
    # Use callbacks to share common setup or constraints between actions.
    def set_app_interaction
      @app_interaction = App::Interaction.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def app_interaction_params
      params.require(:app_interaction).permit(:client_id, :vendor_id, :negotiation_id, :status_id, :description)
    end

    def set_content_for_form

      @vendors = App::Vendor.by_client(get_client_id).order(:name)
      @status = App::StatusInteraction.by_client(get_client_id).order(:name)

      @institutions = App::Institution.by_client(get_client_id).order(:abreviation)
      
      if @app_interaction.present? && @app_interaction.negotiation.present?
        @courses = App::Course.by_client(get_client_id).by_institution(@app_interaction.negotiation.course.institution_id).order(:name)
        @negotiations = App::Negotiation.by_client(get_client_id).by_course(@app_interaction.negotiation.course_id)
      elsif params[:app_interaction].present? && params[:app_interaction][:institution_id].present?
        @courses = App::Course.by_client(get_client_id).by_institution(params[:app_interaction][:institution_id]).order(:name)
        if params[:app_interaction][:course_id].present?
          @negotiations = App::Negotiation.by_client(get_client_id).by_course(params[:app_interaction][:course_id])
        else
          @negotiations = App::Negotiation.none
        end
      else
        @courses =  App::Course.none
        @negotiations =  App::Negotiation.none
      end
      
    end



    def set_content_for_sidebar
      @status = App::StatusInteraction.by_client(get_client_id).order(:name)
      @vendors = App::Vendor.by_client(get_client_id).order(:name)
    end

    def set_variables_for_sidebar(collection)
      @vendors_ids = collection.pluck(:vendor_id).uniq
    end
      
end

app/helpers/app/interactions_helper.rb
module App::InteractionsHelper
end

app/views/app/interactions/_detail.html.erb
<div class="space-y-4">

  <div class="grid grid-cols-1 md:grid-cols-3 gap-4"  >

    <div class="">
      <p class=""><%= App::Interaction.human_attribute_name('institution_id') %></p>
      <div class="relative">
        <%= link_to app_interaction.negotiation.course.institution, class:'detail-input-icon' do %>
          <%= icon('fa-solid', 'building-columns', class:'')%>
        <%end%>
        <p class="detail-input with-icon"><%= app_interaction.negotiation.course.institution.abreviation_and_city %></p>
      </div>
    </div>

    <div class="">
      <p class=""><%= App::Interaction.human_attribute_name('course_id') %></p>

      <div class="relative">
        <%= link_to app_interaction.negotiation.course, class:'detail-input-icon' do %>
          <%= icon('fa-solid', 'chalkboard-user', class:'')%>
        <%end%>
        <p class="detail-input with-icon"><%= app_interaction.negotiation.course.name %></p>
      </div>
    </div>

    <div class="">
      <p class=""><%= App::Interaction.human_attribute_name('negotiation_id') %></p>
      <div class="relative">
        <%= link_to app_interaction.negotiation, class:'detail-input-icon' do %>
          <%= icon('fa-solid', 'users-rectangle', class:'')%>
        <%end%>
        <p class="detail-input with-icon"><%= app_interaction.negotiation.period_in_words_and_calendar %></p>
      </div>
    </div>

  </div>

  <div class="grid grid-cols-1 md:grid-cols-2 gap-4"  >

    <div class="">
      <p class=""><%= App::Negotiation.human_attribute_name('vendor_id') %></p>
      <div class="relative">

        <% if app_interaction.vendor %>
          <%= link_to app_interaction.vendor, class:'detail-input-icon' do %>
            <%= icon('fa-solid', 'user', class:'')%>
          <%end%>

        <% else %>
          <div class="detail-input-icon hover:text-inherit">
            <%= icon('fa-solid', 'user', class:'')%>
          </div>
        <% end %>
        <p class="detail-input with-icon"><%= app_interaction.vendor ? app_interaction.vendor.name : t('activerecord.blank_entries.vendor')%></p>
      </div>
    </div>

    <div class="">
      <p class=""><%= App::Negotiation.human_attribute_name('status') %></p>
      <% if app_interaction.status %>
        <div class="relative text-<%= app_interaction.status.color %>-600 dark:text-<%= app_interaction.status.color %>-600">
          <div class='detail-input-icon hover:text-inherit'>
            <%= icon(app_interaction.status.style, app_interaction.status.icon, class:'')%>
          </div>
          <p class="detail-input with-icon"><%= app_interaction.status.name %></p>
        </div>
      <% else %>
        <div class="relative text-gray-400 dark:text-gray-400">
          <div class='detail-input-icon hover:text-inherit'>
            <%= icon('fa-regular', 'circle', class:'')%>
          </div>
          <p class="detail-input with-icon"><%= t('activerecord.blank_entries.status_negotiation') %></p>
        </div>
      <% end %>
    </div>
  </div>

  <div class="">
    <p class=""><%= App::Interaction.human_attribute_name('description') %></p>
    <div class="detail-input h-auto space-y-6"><%= simple_format(app_interaction.description) %></div>
  </div>

</div>

app/views/app/interactions/_form.html.erb
<%= form_with(model: app_interaction, class: "contents ") do |form| %>
  <% if app_interaction.errors.any? %>
    <% flash.now[:error] = app_interaction.errors.to_a%>
  <% end %>

  <div class="space-y-4">

    <div class="grid grid-cols-1 md:grid-cols-3 gap-4"  data-controller='negotiations'>

      <%# FILTERS  %>
      <div class="">
        <%= form.label :institution_id, class:'required' %>
        <div class="flex justify-between space-x-2 items-center ">
          <div class="relative flex-grow">
            <div class="form-input-icon pt-2"><%= icon('fa-solid','building-columns', class:'') %>  </div>
            <%= form.collection_select :institution_id, @institutions, :id, :abreviation_and_city, {selected: set_selected_institution(app_interaction.negotiation, params[:app_interaction]), include_blank: t('activerecord.blank_entries.general.not_informed')}, {class: "form-input with-icon", data:{action:'change->negotiations#update_courses'}} %>
          </div>
          <%= link_to new_app_institution_path, class: "btn-primary flex-none mt-2 h-10 pt-2.5" do %>
            <%= icon('fa-solid','plus',class:'-mr-2 2xl:-mr-0 btn-icon') %>
            <span class="hidden 2xl:inline"><%= App::Institution.model_name.human %></span>
          <% end %>
        </div>

      </div>

      <div class="">
        <%= form.label :course_id, class:'required' %>
        <div class="flex justify-between space-x-2 items-center ">
          <div class="relative flex-grow">
            <div class="form-input-icon pt-2"><%= icon('fa-solid','chalkboard-user', class:'') %>  </div>
            <%= form.collection_select :course_id, @courses, :id, :name, {selected: set_selected_course(app_interaction.negotiation, params[:app_interaction]), include_blank: t('activerecord.blank_entries.general.not_informed')}, {class: "form-input with-icon", data: {negotiations_target:'courses_select', action:'change->negotiations#update_negotiations'}} %>
          </div>
          <%= link_to new_app_course_path, class: "btn-primary flex-none mt-2 h-10 pt-2.5" do %>
            <%= icon('fa-solid','plus',class:'-mr-2 2xl:-mr-0 btn-icon') %>
            <span class="hidden 2xl:inline"><%= App::Course.model_name.human %></span>
          <% end %>
        </div>
      </div>

      <%#  %>
      <div class="">
        <%= form.label :negotiation_id, class:'required' %>
        <div class="flex justify-between space-x-2 items-center ">
          <div class="relative flex-grow">
            <div class="form-input-icon pt-2"><%= icon('fa-solid','users-rectangle', class:'') %>  </div>
            <%= form.collection_select :negotiation_id, @negotiations, :id, :period_in_words_and_calendar, {selected: app_interaction.negotiation.nil? ? nil : app_interaction.negotiation.id, include_blank: t('activerecord.blank_entries.negotiation_id')}, {class: "form-input with-icon", data: {negotiations_target:'negotiations_select'}} %>
          </div>
          <%= link_to new_app_calendar_path, class: "btn-primary flex-none mt-2 h-10 pt-2.5" do %>
            <%= icon('fa-solid','plus',class:'-mr-2 2xl:-mr-0 btn-icon') %>
            <span class="hidden 2xl:inline"><%= App::Calendar.model_name.human %></span>
          <% end %>
        </div>
      </div>

    </div>

    <div class="grid grid-cols-1 md:grid-cols-2 gap-4"  >

      <div class="">
        <%= form.label :vendor_id, class:'required' %>
        <div class="flex justify-between space-x-2 items-center ">
          <div class="relative flex-grow">
            <div class="form-input-icon pt-2"><%= icon('fa-solid','user', class:'') %>  </div>
            <%= form.collection_select :vendor_id, @vendors, :id, :name, {selected: get_current_access.vendor ? get_current_access.vendor_id : nil, include_blank: t('activerecord.blank_entries.general.not_informed')}, {class: "form-input with-icon"} %>
          </div>
          <%= link_to new_app_vendor_path, class: "btn-primary flex-none mt-2 h-10 pt-2.5" do %>
            <%= icon('fa-solid','plus',class:'-mr-2 2xl:-mr-0  btn-icon') %>
            <span class="hidden 2xl:inline"><%= App::Vendor.model_name.human %></span>
          <% end %>
        </div>
      </div>

      <div class="">
        <%= form.label :status_id, class:'required' %>
        <div class="flex justify-between space-x-2 items-center ">
          <div class="relative flex-grow">
            <div class="form-input-icon pt-2"><%= icon('fa-solid','circle-question', class:'') %>  </div>
            <%= form.collection_select :status_id, @status, :id, :name, {include_blank: t('activerecord.blank_entries.general.not_informed')}, {class: "form-input with-icon"} %>
          </div>
          <%= link_to new_app_status_interaction_path, class: "btn-primary flex-none mt-2 h-10 pt-2.5" do %>
            <%= icon('fa-solid','plus',class:'-mr-2 2xl:-mr-0  btn-icon') %>
            <span class="hidden 2xl:inline"><%= App::StatusInteraction.model_name.human %></span>
          <% end %>
        </div>
      </div>
    </div>

    <div class="col-span-2">
      <%= form.label :description, class:'required' %>
      <%= form.text_area :description, rows: 4, class: "form-input h-auto", data: {controller:"textarea-autogrow"}, placeholder: t('activerecord.placeholders.app/interaction.description')%>
    </div>

  </div>

  <div class="mt-4 inline-flex w-full justify-end">
    <%= form.submit class: "btn-primary" %>
  </div>

<% end %>

app/views/app/interactions/_interaction.html.erb
<div id="<%= dom_id interaction %>" data-turbo="false" data-aos="fade" class='card group' data-controller="reveal" data-reveal-hidden-class="grid" >

  <div class="card-header">

    <div class="card-header-info card-header-animate ">
      <p class="overflow-scroll scrollbar-hide truncate text-<%=interaction.status.color%>-600 dark:text-<%=interaction.status.color%>-600 ">
        <%= link_to  interaction, class:'card-header-title' do %>
         <%= icon(interaction.status.style, interaction.status.icon, class:"mr-1") %>
         <%= interaction.status.name %>
        <%end%>
      </p>
      <p class="card-header-subtitle card-header-subtitle-animate truncate"><%= time_ago_in_words(interaction.created_at) %> - <%= interaction.vendor.name %></p>
    </div>

    <%= button_tag class:'card-header-btn', data: { action:"click->reveal#toggle" } do %>
      <%= icon('fa-solid','bars', class:'fa-sm')%>
    <%end%>

  </div>

  <%# CARD BODY %>

  <div class="card-tag-readonly relative"  data-controller="reveal" data-action="mouseleave->reveal#hide"> 
    <%= button_tag interaction.negotiation.course.name, data: {action:"click->reveal#show"}, class:'w-full truncate'%>
    
    <div data-reveal-target="item" class="hidden absolute bg-gray-200 w-full -top-11 left-0 pt-1.5 rounded-t-md" >
      <p class="truncate "><%= icon('fa-solid', 'building-columns', class:'mr-1')%> <%= interaction.negotiation.course.institution.abreviation_and_city %></p>
      <p class="truncate"><%= interaction.negotiation.period_in_words %></p>
    </div>
  </div>
  
  <%# END BODY %>

 

  <div data-reveal-target="item" class="card-popover <% if !can_set_vendor?(interaction)%> w-24 grid-cols-1<%end%>" data-action="mouseleave->reveal#show">

    <%= link_to edit_app_interaction_path(interaction), class:'card-popover-btn-primary w-full' do %>
      <%= icon('fa-solid', 'pen-to-square', class:'btn-icon') %>
      <p class=""> <%= t('views.app.general.edit')%></p>
    <%end%>
    

    <%= button_to app_interaction_path(interaction), method: :patch, form_class: "", class:'card-popover-btn-primary flex-none ', params: { app_interaction: { vendor_id: get_current_access.vendor_id } } do %>
      <%= icon('fa-solid','check-to-slot',class:'btn-icon') %>
      <%= t('views.app.interactions.button.set_vendor') %>
    <%end if can_set_vendor?(interaction)%>


  </div>

</div>

app/views/app/interactions/_interactions.html.erb
<div class="gap-4 mb-5">

  <%# TURBO_STREAM CONTENT APPEND WILL APPEAR HERE %>
  <%= turbo_frame_tag "app_collection_list",  class:'default-grid',  loading: :lazy, 
                        src: send(@collection_src_url,  page: params[:page], format: "turbo_stream",
                                  query: params[:query], status_ids: params[:status_ids], vendor_ids: params[:vendor_ids]) %>
  <%# ---------------------------------------------------- %>

  <%# CONTENT FOR TURBO PAGINATION WITH INFINITE SCROLL %>
  <%= turbo_frame_tag "app_collection_pagination" %>
  <%# ---------------------------------------------------- %>

</div>

app/views/app/interactions/_sidebar.html.erb
<div class="" data-controller="search reveal">

  <div class="detail-input text-xs text-center h-8 -mb-1" id="pagy_info">
    <%== pagy_info(@pagy, item_name: App::Interaction.model_name.human(count: @pagy.items )) %>
  </div>

  <%= form_with url: search_app_interactions_path, method: :get, class:'space-y-1' do |form| %>

    <%# SEACH INPUT %>
    <div class="relative" data-action='mouseenter->reveal#toggle mouseleave->reveal#toggle '>
      <div class="search-input-icon dark:hover:bg-blue-600" data-action="click->search#submit"><%= icon('fa-solid','search', class:'fa-sm ') %>  </div>
      <%= form.text_field :query, value:params[:query],  class:'search-input text-sm', placeholder: t('views.app.general.search'), data: {action: 'keydown.enter->search#submit'} %>
    </div>
    <div class="hidden detail-input text-xs h-8 " data-reveal-target="item">
      <p class="text-center"> 
      <%= %i[ description ].map{|attr| App::Interaction.human_attribute_name(attr)}.join(" | ")  %>
      </p>
    </div>
    <%# END OF SEARCH INPUT%>


   <%# STATUS NEGOTIATIONS INPUT %>
    <% if @status.present? %>
      <div class="bg-gray-100 dark:bg-gray-900 py-2 px-3 space-y-1 rounded-lg text-sm">
        <%= button_tag t('views.app.general.select_all_m'), type: "button", class: "w-full bg-gray-200 dark:bg-gray-800 hover:bg-blue-600 hover:text-white dark:hover:bg-blue-600 p-1 rounded-lg text-sm", data: { action: "search#selectAll search#submit" } if @status.any?%>
        <%= form.collection_check_boxes  :status_ids, @status, :id, :name, include_hidden: false do |status| %>
          <div class="mt-0 flex justify-between items-center">
            <div class="truncate">
              <%= status.check_box(class: 'form-checkbox-simple dark:bg-gray-800 bg-gray-200 mr-1 ', checked: (params[:status_ids].present? && params[:status_ids].include?(status.value.to_s)  ), data: {action: ' change->search#submit'}) %>
              <%= status.label class:'cursor-pointer text-sm' do %>
                <%= status.text %>
              <% end %>
            </div>
            <%= icon('fa-solid', 'bolt', class:'p-1.5 bg-gray-200 dark:bg-gray-800 rounded-lg hover:text-blue-600 cursor-pointer', data: { action:" click->search#selectOnly  click->search#submit"} )%>
          </div>
        <% end %>
      </div>
    <% end %>
    <%# END OF STATUS NEGOTIATIONS INPUT%>

    <%# VENDOR NEGOTIATIONS INPUT %>
    <% if @vendors.present? %>
      <div class="bg-gray-100 dark:bg-gray-900 py-2 px-3 space-y-1 rounded-lg text-sm">
        <%= button_tag t('views.app.general.select_all_m'), type: "button", class: "w-full bg-gray-200 dark:bg-gray-800 hover:bg-blue-600 hover:text-white dark:hover:bg-blue-600 p-1 rounded-lg text-sm", data: { action: "search#selectAll search#submit" } if @vendors.any?%>
        <%= form.collection_check_boxes  :vendor_ids, @vendors, :id, :name, include_hidden: false do |vendor| %>
          <div class="mt-0 flex justify-between items-center">
            <div class="truncate">
              <%= vendor.check_box(class: 'form-checkbox-simple dark:bg-gray-800 bg-gray-200 mr-1 ', checked: (params[:vendor_ids].present? && params[:vendor_ids].include?(vendor.value.to_s) || (action_name=='index' && get_current_access.vendor_id == vendor.value) ), data: {action: ' change->search#submit'}) %>
              <%= vendor.label class:'cursor-pointer text-sm ' do %>
                <%= vendor.text %>
              <% end %>
            </div>
            <%= icon('fa-solid', 'bolt', class:'p-1.5 bg-gray-200 dark:bg-gray-800 rounded-lg hover:text-blue-600 cursor-pointer', data: { action:" click->search#selectOnly  click->search#submit"} )%>
          </div>
        <% end %>
      </div>
    <% end %>
    <%# END OF VENDOR NEGOTIATIONS INPUT%>


  
  <% end %>

</div>

app/views/app/interactions/edit.html.erb
<% content_for :ctas_secondary do %>
  <%= link_to app_interactions_path, class: "btn-secondary-gray flex-none" do %>
    <%= icon('fa-solid','arrow-left', class:'-mx-1')%>
  <%end%>

  <%= link_to app_interaction_path(@app_interaction), class: "btn-secondary flex-none" do %>
    <%= icon('fa-solid','arrow-up-right-from-square', class:'-mx-1')%>
  <%end%>

<% end %>

<% provide :head_title, "#{t('views.app.general.editing')} #{App::Interaction.model_name.human}" %>
<% provide :page_title, "#{t('views.app.general.editing')} #{App::Interaction.model_name.human}" %>
<% provide :entry_id, "#{@app_interaction.id}" %>

<% content_for :page_content do %>
  <%= render "form", app_interaction: @app_interaction %>
<%end%>

app/views/app/interactions/index.html.erb
<% content_for :ctas_primary do %>
  <%= link_to new_app_interaction_path, class: "btn-primary flex-none" do %>
    <%= icon('fa-solid','plus',class:'btn-icon') %>
    <%= App::Interaction.model_name.human %>
  <% end %>
<% end %>

<% provide :head_title, App::Interaction.model_name.human(count:2) %>
<% provide :page_title, App::Interaction.model_name.human(count:2) %>
<% provide :sidebar, render(partial: 'app/interactions/sidebar') %>

<% content_for :page_content do %>
  <%= render partial: "interactions" %>
<%end%>

app/views/app/interactions/index.turbo_stream.erb
<!-- append content to turbo_frame -->
<%= turbo_stream.append("app_collection_list") do %>
  <%= render @app_interactions %>
<% end %>

<!-- replace #article_pagination frame by our content loader when it gets visible (our turbo_frame_tag with loading="lazy" attribute -->
<% if @pagy.next.present? %>
   
    <%= turbo_stream.replace "app_collection_pagination" do %>
    <%= turbo_frame_tag "app_collection_pagination", loading: "lazy", 
                           src:  send(@collection_src_url, page: @pagy.next, format: "turbo_stream", 
                                       query: params[:query], status_ids: params[:status_ids], vendor_ids: params[:vendor_ids]) %>
     
    
    <% end %>
 
<% end %>

<%# update # %>
<%= turbo_stream.update "pagy_info" do %>
  <%== pagy_info(@pagy, item_name: App::Interaction.model_name.human(count: @pagy.items)) %>
<%end%>

app/views/app/interactions/new.html.erb
<% content_for :ctas_secondary do %>
  <%= link_to app_interactions_path, class: "btn-secondary-gray flex-none" do %>
    <%= icon('fa-solid','arrow-left', class:'-mx-1')%>
  <%end%>
<% end %>

<% provide :page_title, "#{t('views.app.general.new')} #{App::Interaction.model_name.human}" %>

<% content_for :page_content do %>
  <%= render "form", app_interaction: @app_interaction %>
<%end%>

app/views/app/interactions/show.html.erb
<% content_for :ctas_secondary do %>
  <%= link_to app_interactions_path, class: "btn-secondary-gray flex-none" do %>
    <%= icon('fa-solid','arrow-left', class:'-mx-1')%>
  <%end%>

  <%= link_to edit_app_interaction_path(@app_interaction), class: "btn-secondary flex-none" do %>
    <%= icon('fa-solid','pen-to-square', class:'-mx-1')%>
  <%end%>

  <%= button_to app_interaction_path(@app_interaction),  method: :delete, data: { turbo: false },onclick: "return confirm('#{t('views.app.general.delete_confirm')}')", class: "btn-delete flex-none" do %>
    <%= icon('fa-solid','trash-can', class:'-mx-1')%>
  <%end%>

<% end %>

<% provide :head_title, "#{t('views.app.general.showing')} #{App::Interaction.model_name.human} " %>
<% provide :page_title, "#{t('views.app.general.showing')} #{App::Interaction.model_name.human} " %>
<% provide :entry_id, "#{@app_interaction.id}" %>

<% content_for :page_content do %>
  <%= render "detail", app_interaction: @app_interaction %>
<%end%>