config/routes.rb
Rails.application.routes.draw do

  devise_for :admins, class_name: "App::Admin", controllers: { sessions: 'admins/sessions'}
  devise_for :users, class_name: "App::User", controllers: { sessions: 'users/sessions'}
  
  root to: "site#index", as: :site_root
  
  # - - - - - - - - - - ROUTES FOR SITE - - - - - - - - - - 

  get 'unsubscribe', to: 'app/subscribers#unsubscribe', as: :unsubscribe
  post '/toogle_locale', to: 'site#toogle_locale', as: :toogle_locale
  post '/contact_forms', to: 'site#contact_forms', as: :contact_forms

  get '/:slug', to: 'app/prospects#new_by_slug'

  # - - - - - - - - - - ROUTES FOR APPLICATION - - - - - - - - - - 


  devise_scope :user do
    authenticated :user do
      root 'app/users#index', as: :user_authenticated_root
    end

    unauthenticated do
      namespace :app do
        root 'devise/sessions#new', as: :unauthenticated_root
      end
    end
  end

  devise_scope :admins do 
    authenticated :admin do
      root 'app/clients#index', as: :admin_authenticated_root
      
      # Exclusive routes in App namespace (just for admin)
      namespace :app do
        resources :admins, only: [:update]
        resources :clients do
          delete :destroy_attachment, on: :member
          get :search, on: :collection
          post :recalculate_periods, on: :collection
        end
        resources :subscribers, only: [:index]
        resources :updates 
      end
    end
  end

  # Commom routes in App namespace
  namespace :app do
    resources :role_vendors do
      get :search, on: :collection
    end
    resources :interactions do 
      get :search, on: :collection
    end

    resources :status_interactions do
      get :search, on: :collection
    end
    resources :contacts do 
      get :search, on: :collection
    end

    resources :classes, only: [:index] do
      get :search, on: :collection
    end 


    resources :negotiations, except: %i[new create destroy] do
      get :search, on: :collection
      get :filter, on: :collection
    end

    resources :status_negotiations do
      get :search, on: :collection
    end

    get :settings, to: 'settings#index'

    resources :companies do
      get :search, on: :collection
    end

    resources :calendars do
      get :search, on: :collection
      delete :destroy_confirm, on: :member
    end

    resources :courses do 
      get :search, on: :collection
      get :filter, on: :collection
    end
  
    resources :institutions do
        get :search, on: :collection
        delete :destroy_attachment, on: :member
    end
    
    resources :prospects do 
      get :search, on: :collection
    end
    resources :vendors do 
      get :search, on: :collection
    end

    resources :cities do 
      get :filter, on: :collection
      get :search, on: :collection
    end
    
    resources :users do
      get :search, on: :collection
    end
    resources :subscribers, only: [:create, :destroy]
    resources :updates, only: [:index, :show]
  end
  
end

app/models/app/role_vendor.rb
class App::RoleVendor < ApplicationRecord
  belongs_to :client, class_name: 'App::Client'
  has_many :vendors, class_name: 'App::Vendor', foreign_key: 'role_id'

  # Validations
  validates :name, presence: true, uniqueness: { scope: :client_id }
  

   # Scope
   include App::Scopes
   scope :search, -> (search) { where("LOWER(UNACCENT(name)) LIKE LOWER(UNACCENT(:search))", search: "%#{search}%") }
   scope :by_role_vendor_status, -> (status) do 
     case status
       when 'active'
         where(active: true)
       when 'not_active'
         where(active: false)
     end
   end
 
 
   #  Methods
   def has_dependency?
     self.vendors.any?
   end

end

app/controllers/app/role_vendors_controller.rb
class App::RoleVendorsController < ApplicationController
  before_action :set_app_role_vendor, only: %i[ show edit update destroy ]

  # GET /app/role_vendors or /app/role_vendors.json
  def index
    collection = App::RoleVendor.by_client(get_client_id).order(:name)
    @pagy,  @app_role_vendors = set_pagy(collection)
  end

  # GET /app/role_vendors/1 or /app/role_vendors/1.json
  def show
  end

  # GET /app/role_vendors/new
  def new
    @app_role_vendor = App::RoleVendor.new(active: true)
  end

  # GET /app/role_vendors/1/edit
  def edit
  end

  # POST /app/role_vendors or /app/role_vendors.json
  def create
    @app_role_vendor = App::RoleVendor.new(app_role_vendor_params)
    set_client_id(@app_role_vendor)

    if @app_role_vendor.save
      flash[:success] = t('views.app.general.flash.create_m', model: App::RoleVendor.model_name.human)
      redirect_to app_role_vendor_url(@app_role_vendor)
    else
        render :new, status: :unprocessable_entity 
    end
  end

  # PATCH/PUT /app/role_vendors/1 or /app/role_vendors/1.json
  def update
    if @app_role_vendor.update(app_role_vendor_params)
      flash[:success] = t('views.app.general.flash.update_m', model: App::RoleVendor.model_name.human)
      redirect_to app_role_vendor_url(@app_role_vendor)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /app/role_vendors/1 or /app/role_vendors/1.json
  def destroy
    if @app_role_vendor.has_dependency?
      flash[:error] = t('views.app.general.flash.destroy_failed_m', model: App::RoleVendor.model_name.human)
      redirect_to @app_role_vendor
    else
      @app_role_vendor.destroy
      flash[:success] = t('views.app.general.flash.destroy_m', model: App::RoleVendor.model_name.human)
      redirect_to app_role_vendors_path
    end
  end


   #  GET /app/role_vendors/search?query=:query&status=:status
   def search 

    collection = App::RoleVendor.by_client(get_client_id)

    collection = collection.by_role_vendor_status(params[:status])
    collection = collection.search(params[:query].to_s) if params[:query].present?

    @pagy,  @app_role_vendors = set_pagy(collection)
    
    render :index

  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_app_role_vendor
      @app_role_vendor = App::RoleVendor.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def app_role_vendor_params
      params.require(:app_role_vendor).permit( :name, :active)
    end
end

app/helpers/app/role_vendors_helper.rb
module App::RoleVendorsHelper
end

app/views/app/role_vendors/_detail.html.erb
<div class="space-y-4">

  <%# DETAILS %>
  <div class="grid grid-cols-1 md:grid-cols-3 gap-4">

    <div class="md:col-span-2">
      <p class=""><%= App::RoleVendor.human_attribute_name('name') %></p>
      <p class="detail-input "><%= app_role_vendor.name%></p>
    </div>

    <div class="">
      <p class=""><%= App::RoleVendor.human_attribute_name('active') %></p>

      <% if app_role_vendor.active %>
        <div class="text-base detail-input dark:bg-blue-600 bg-blue-600 text-white text-center rounded-lg"> <%= icon('fa-solid','check')%> <%= t('activerecord.options.app/role_vendor.active.true')%></div>
      <% else %>
        <div class="text-base detail-input bg-gray-100 text-red-600 text-center rounded-lg "> <%= icon('fa-solid','xmark')%> <%= t('activerecord.options.app/role_vendor.active.false')%></div>
      <% end %>
    </div>


  </div>

</div>

app/views/app/role_vendors/_form.html.erb
<%= form_with(model: app_role_vendor, class: "contents") do |form| %>
  <% if app_role_vendor.errors.any? %>
    <% flash.now[:error] = app_role_vendor.errors.to_a%>
  <% end %>

  <div class="grid grid-cols-1 md:grid-cols-3 gap-4">
   
    <div class="md:col-span-2">
      <%= form.label :name, class:'required' %>
      <%= form.text_field :name, class: "form-input" %>
    </div>

    <div class=" group mb-2">
      <%= form.label :active, class:'pointer-events-none' %>
      <%= form.check_box :active, class: "hidden peer" %>
      <%= form.label :active, class:'form-checkbox w-full  dark:bg-gray-900
    group-hover:bg-gray-100        group-hover:peer-checked:bg-blue-700  
    dark:group-hover:bg-gray-950   dark:group-hover:peer-checked:bg-blue-700' do %>
      <% end %>

      <div class="text-base peer-text hidden peer-checked:block "> <%= icon('fa-solid','check')%> <%= t('activerecord.options.app/status_interaction.active.true')%></div>
      <div class="text-base peer-text block peer-checked:hidden "> <%= icon('fa-solid','xmark')%> <%= t('activerecord.options.app/status_interaction.active.false')%></div>
    </div>
  </div>

  <div class="mt-4 inline-flex w-full justify-end">
    <%= form.submit class: "btn-primary" %>
  </div>
<% end %>

app/views/app/role_vendors/_role_vendor.html.erb
<div id="<%= dom_id role_vendor %>"  data-aos='fade' class='card group' data-controller="reveal" data-reveal-hidden-class="grid">

  <div class="card-header">

    <div class="card-header-info my-auto">
      <p class="overflow-scroll scrollbar-hide ">
        <%= link_to app_role_vendor_path(role_vendor), class:'card-header-title' do %>
          <%= role_vendor.name %>
        <%end%>
      </p>

    </div>

    <%= button_tag class:'card-header-btn',  data: { action:"click->reveal#toggle" } do %>
      <%= icon('fa-solid','bars', class:'fa-sm')%>
    <%end%>

  </div>

  <div data-reveal-target="item" class="card-popover w-24" data-action="mouseleave->reveal#show">

    <%= link_to edit_app_role_vendor_path(role_vendor), class:'card-popover-btn-primary' do %>
      <%= icon('fa-solid', 'pen-to-square', class:'btn-icon') %>
      <p class=""> <%= t('views.app.general.edit')%></p>
    <%end%>

  </div>

</div>

app/views/app/role_vendors/_role_vendors.html.erb
<div class="default-grid">
  <%= render @app_role_vendors %>
</div>

app/views/app/role_vendors/_sidebar.html.erb
<div class="" data-controller='search reveal' data-reveal-hidden-class="hidden">
  <div class="detail-input text-xs text-center h-8 -mb-1" id="pagy_info">
   <%== pagy_info(@pagy, item_name: App::StatusInteraction.model_name.human(count: @pagy.items)) %>
  </div>
  
  <%= form_with(url: search_app_role_vendors_path, method: :get,  class:'space-y-1') do |form| %>

    <%# SEACH INPUT %>
    <div class="relative" data-action='mouseenter->reveal#toggle mouseleave->reveal#toggle '>
      <div class="search-input-icon dark:hover:bg-blue-600" data-action="click->search#submit"><%= icon('fa-solid','search', class:'fa-sm ') %>  </div>
      <%= form.text_field :query, value:params[:query], class:'search-input text-sm', placeholder: t('views.app.general.search'), data: {action: 'keydown.enter->search#submit'} %>
    </div>
    <div class="hidden  detail-input text-xs h-8 " data-reveal-target="item">
      <p class="text-center">
        <%= %i[ name ].map{|attr| App::StatusInteraction.human_attribute_name(attr)}.join(" | ")  %>
      </p>
    </div>
    <%# END OF SEARCH INPUT%>

    <%# STATUS INPUT %>

    <%= form.label "status_all", class:'detail-input cursor-pointer mt-0' do %>
      <%= form.radio_button :status, 'all', class:'form-radio-simple mr-1', id:"status_all", checked: (true), data: {action: 'change->search#submit'} %>
      <span class="text-sm"><%= t('activerecord.options.app/role_vendor.active.all') %></span>
    <% end %>

    <%= form.label "status_active", class:'detail-input cursor-pointer mt-0' do %>
      <%= form.radio_button :status, 'active', class:'form-radio-simple mr-1', id:"status_active", checked: params[:status] == 'active', data: {action: 'change->search#submit'} %>
      <span class="text-sm"><%= t('activerecord.options.app/role_vendor.active.true') %></span>
    <% end %>

    <%= form.label "status_not_active", class:'detail-input cursor-pointer mt-0' do %>
      <%= form.radio_button :status, 'not_active', class:'form-radio-simple mr-1', id:"status_not_active", checked: params[:status] == 'not_active', data: {action: 'change->search#submit'} %>
      <span class="text-sm"><%= t('activerecord.options.app/role_vendor.active.false') %></span>
    <% end %>

    <%# END OF STATUS %>


    

  <% end %>

</div>

app/views/app/role_vendors/edit.html.erb
<% content_for :ctas_secondary do %>
  <%= link_to app_role_vendors_path, class: "btn-secondary-gray flex-none" do %>
    <%= icon('fa-solid','arrow-left', class:'-mx-1')%>
  <%end%>

  <%= link_to app_role_vendor_path(@app_role_vendor), class: "btn-secondary flex-none" do %>
    <%= icon('fa-solid','arrow-up-right-from-square', class:'-mx-1')%>
  <%end%>
<% end %>

<% provide :head_title, "#{t('views.app.general.editing')} #{App::StatusInteraction.model_name.human}" %>
<% provide :page_title, "#{t('views.app.general.editing')} #{App::StatusInteraction.model_name.human}" %>
<% provide :entry_id, "#{@app_role_vendor.id}" %>

<% content_for :page_content do %>
  <%= render "form", app_role_vendor: @app_role_vendor %>
<%end%>

app/views/app/role_vendors/index.html.erb
<% content_for :ctas_primary do %>
  <%= link_to new_app_role_vendor_path, class: "btn-primary flex-none" do %>
    <%= icon('fa-solid','plus',class:'btn-icon') %>
    <%= App::RoleVendor.model_name.human %>
  <% end %>
<% end %>

<% content_for :ctas_secondary do %>
  <%= link_to app_settings_path, class: "btn-secondary-gray flex-none" do %>
    <%= icon('fa-solid','arrow-left', class:'-mx-1')%>
  <%end%>
<%end%>


<% provide :head_title, App::RoleVendor.model_name.human(count:2) %>
<% provide :page_title, App::RoleVendor.model_name.human(count:2) %>
<% provide :sidebar, render(partial: 'app/role_vendors/sidebar') %>

<% content_for :page_content do %>

  <%= render partial: 'role_vendors' %>
<%end%>

app/views/app/role_vendors/new.html.erb
<% content_for :ctas_secondary do %>
  <%= link_to app_role_vendors_path, class: "btn-secondary-gray flex-none" do %>
    <%= icon('fa-solid','arrow-left', class:'-mx-1')%>
  <%end%>
<% end %>

<% provide :page_title, "#{t('views.app.general.new')} #{App::RoleVendor.model_name.human}" %>

<% content_for :page_content do %>
  <%= render "form", app_role_vendor: @app_role_vendor %>
<%end%>

app/views/app/role_vendors/show.html.erb
<% content_for :ctas_secondary do %>
  <%= link_to app_role_vendors_path, class: "btn-secondary-gray flex-none" do %>
    <%= icon('fa-solid','arrow-left', class:'-mx-1')%>
  <%end%>

  <%= link_to edit_app_role_vendor_path(@app_role_vendor), class: "btn-secondary flex-none" do %>
    <%= icon('fa-solid','pen-to-square', class:'-mx-1')%>
  <%end%>

  <%= button_to app_role_vendor_path(@app_role_vendor), method: :delete, data: { turbo: false },onclick: "return confirm('#{t('views.app.general.delete_confirm')}')", class: "btn-delete flex-none" do %>
    <%= icon('fa-solid','trash-can', class:'-mx-1')%>
  <%end unless @app_role_vendor.has_dependency?%>
<% end %>

<% content_for :ctas_primary do %>

  <%= link_to new_app_vendor_path(role_id: @app_role_vendor.id), class: "btn-primary flex-none" do %>
    <%= icon('fa-solid','plus',class:'btn-icon') %>
    <%= App::Vendor.model_name.human %>
  <% end %>

  <%= link_to search_app_vendors_path(role_ids: [@app_role_vendor.id]), class: "btn-primary flex-none" do %>
    <%= icon('fa-solid','user-group',class:'btn-icon') %>
    <%= App::Vendor.model_name.human(count:2) %>
  <% end %>

<% end %>

<% provide :head_title, "#{t('views.app.general.showing')} #{App::RoleVendor.model_name.human} " %>
<% provide :page_title, "#{t('views.app.general.showing')} #{App::RoleVendor.model_name.human} " %>
<% provide :entry_id, "#{@app_role_vendor.id}" %>

<% content_for :page_content do %>
  <%= render "detail", app_role_vendor: @app_role_vendor %>
<%end%>