config/routes.rb
Rails.application.routes.draw do

  devise_for :admins, class_name: "App::Admin", controllers: { sessions: 'admins/sessions'}
  devise_for :users, class_name: "App::User", controllers: { sessions: 'users/sessions'}
  
  root to: "site#index", as: :site_root
  
  # - - - - - - - - - - ROUTES FOR SITE - - - - - - - - - - 

  get 'unsubscribe', to: 'app/subscribers#unsubscribe', as: :unsubscribe
  post '/toogle_locale', to: 'site#toogle_locale', as: :toogle_locale
  post '/contact_forms', to: 'site#contact_forms', as: :contact_forms

  get '/:slug', to: 'app/prospects#new_by_slug'

  # - - - - - - - - - - ROUTES FOR APPLICATION - - - - - - - - - - 


  devise_scope :user do
    authenticated :user do
      root 'app/users#index', as: :user_authenticated_root
    end

    unauthenticated do
      namespace :app do
        root 'devise/sessions#new', as: :unauthenticated_root
      end
    end
  end

  devise_scope :admins do 
    authenticated :admin do
      root 'app/clients#index', as: :admin_authenticated_root
      
      # Exclusive routes in App namespace (just for admin)
      namespace :app do
        resources :admins, only: [:update]
        resources :clients do
          delete :destroy_attachment, on: :member
          get :search, on: :collection
          post :recalculate_periods, on: :collection
        end
        resources :subscribers, only: [:index]
        resources :updates 
      end
    end
  end

  # Commom routes in App namespace
  namespace :app do
    resources :role_vendors do
      get :search, on: :collection
    end
    resources :interactions do 
      get :search, on: :collection
    end

    resources :status_interactions do
      get :search, on: :collection
    end
    resources :contacts do 
      get :search, on: :collection
    end

    resources :classes, only: [:index] do
      get :search, on: :collection
    end 


    resources :negotiations, except: %i[new create destroy] do
      get :search, on: :collection
      get :filter, on: :collection
    end

    resources :status_negotiations do
      get :search, on: :collection
    end

    get :settings, to: 'settings#index'

    resources :companies do
      get :search, on: :collection
    end

    resources :calendars do
      get :search, on: :collection
      delete :destroy_confirm, on: :member
    end

    resources :courses do 
      get :search, on: :collection
      get :filter, on: :collection
    end
  
    resources :institutions do
        get :search, on: :collection
        delete :destroy_attachment, on: :member
    end
    
    resources :prospects do 
      get :search, on: :collection
    end
    resources :vendors do 
      get :search, on: :collection
    end

    resources :cities do 
      get :filter, on: :collection
      get :search, on: :collection
    end
    
    resources :users do
      get :search, on: :collection
    end
    resources :subscribers, only: [:create, :destroy]
    resources :updates, only: [:index, :show]
  end
  
end

app/models/app/status_negotiation.rb
class App::StatusNegotiation < ApplicationRecord
  belongs_to :client, class_name: 'App::Client'
  has_many :negotiations, class_name: 'App::Negotiation', foreign_key: 'status_id'

  # Constants
  COLORS = %w[default red amber orange yellow lime green emerald teal cyan sky blue indigo violet purple fuchsia pink rose ].freeze
  STYLES = %w[fa-solid fa-regular fa-brands].freeze

  # Validations
  validates :name, presence: true, uniqueness: { scope: :client_id }
  
  # Scope
  include App::Scopes
  scope :search, -> (search) { where("LOWER(UNACCENT(name)) LIKE LOWER(UNACCENT(:search))", search: "%#{search}%") }
  scope :by_status_negotiation_status, -> (status) do 
    case status
      when 'active'
        where(active: true)
      when 'not_active'
        where(active: false)
    end
  end


  #  Methods
  def has_dependency?
    self.negotiations.any?
  end
end

app/controllers/app/status_negotiations_controller.rb
class App::StatusNegotiationsController < ApplicationController
  before_action :set_form_variables, only: %i[ new edit create update ]
  before_action :set_app_status_negotiation, only: %i[ show edit update destroy ]

  # GET /app/status_negotiations or /app/status_negotiations.json
  def index
    collection = App::StatusNegotiation.by_client(get_client_id).order(:name)
    @pagy,  @app_status_negotiations = set_pagy(collection)
  end

  # GET /app/status_negotiations/1 or /app/status_negotiations/1.json
  def show
  end

  # GET /app/status_negotiations/new
  def new
    @app_status_negotiation = App::StatusNegotiation.new
  end

  # GET /app/status_negotiations/1/edit
  def edit
  end

  # POST /app/status_negotiations or /app/status_negotiations.json
  def create
    @app_status_negotiation = App::StatusNegotiation.new(app_status_negotiation_params)
    set_client_id(@app_status_negotiation)

    if @app_status_negotiation.save
      flash[:success] = t('views.app.general.flash.create_f', model: App::StatusNegotiation.model_name.human)
      redirect_to app_status_negotiation_url(@app_status_negotiation)
    else
        render :new, status: :unprocessable_entity 
    end
  end

  # PATCH/PUT /app/status_negotiations/1 or /app/status_negotiations/1.json
  def update
    if @app_status_negotiation.update(app_status_negotiation_params)
      flash[:success] = t('views.app.general.flash.update_f', model: App::StatusNegotiation.model_name.human)
      redirect_to app_status_negotiation_url(@app_status_negotiation)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /app/status_negotiations/1 or /app/status_negotiations/1.json
  def destroy
    if @app_status_negotiation.has_dependency?
      flash[:error] = t('views.app.general.flash.destroy_failed_f', model: App::StatusNegotiation.model_name.human)
      redirect_to @app_status_negotiation
    else
      @app_status_negotiation.destroy
      flash[:success] = t('views.app.general.flash.destroy_f', model: App::StatusNegotiation.model_name.human)
      redirect_to app_status_negotiations_path
    end
  end

   #  GET /app/calendars/search?query=:query&status=:status
   def search 

    collection = App::StatusNegotiation.by_client(get_client_id)

    collection = collection.by_status_negotiation_status(params[:status])
    collection = collection.search(params[:query].to_s) if params[:query].present?

    @pagy,  @app_status_negotiations = set_pagy(collection)
    
    render :index

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_app_status_negotiation
      @app_status_negotiation = App::StatusNegotiation.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def app_status_negotiation_params
      params.require(:app_status_negotiation).permit(:name, :active, :icon, :style, :color)
    end

    def set_form_variables
      @styles = App::StatusNegotiation::STYLES.map{ |style| [style, t("activerecord.options.general.STYLE.#{style}")]}
    end
end

app/helpers/app/status_negotiations_helper.rb
module App::StatusNegotiationsHelper
  def get_bg_color_for(status)
    return "bg-gray-600" unless status.color.present?
    "bg-#{status.color}-600"
  end

  def get_text_color_for(status)
    return "text-#{status.color}-600" if status.color == 'default'
    "text-#{status.color}-600"
  end
end

app/views/app/status_negotiations/_detail.html.erb
<div class="space-y-4">

  <%# DETAILS %>
  <div class="grid grid-cols-1 md:grid-cols-3 gap-4">

    <div class="md:col-span-2">
      <p class=""><%= App::StatusNegotiation.human_attribute_name('name') %></p>
      <p class="detail-input "><%= app_status_negotiation.name%></p>
    </div>

    <div class="">
      <p class=""><%= App::StatusNegotiation.human_attribute_name('active') %></p>

      <% if app_status_negotiation.active %>
        <div class="text-base detail-input dark:bg-blue-600 bg-blue-600 text-white text-center rounded-lg"> <%= icon('fa-solid','check')%> <%= t('activerecord.options.app/status_negotiation.active.true')%></div>
      <% else %>
        <div class="text-base detail-input bg-gray-100 text-red-600 text-center rounded-lg "> <%= icon('fa-solid','xmark')%> <%= t('activerecord.options.app/status_negotiation.active.false')%></div>
      <% end %>
    </div>

   <div class="">
      <p class=""><%= App::StatusNegotiation.human_attribute_name('icon') %></p>
      <p class="detail-input text-<%= app_status_negotiation.color%>-600">
        <%= icon(app_status_negotiation.style, app_status_negotiation.icon) %>
        <%= app_status_negotiation.name%>
      </p>
    </div>


  </div>

</div>

app/views/app/status_negotiations/_form.html.erb
<%= form_with(model: app_status_negotiation, class: "contents") do |form| %>
  <% if app_status_negotiation.errors.any? %>
    <% flash.now[:error] = app_status_negotiation.errors.to_a%>
  <% end %>

  <div class="grid grid-cols-1 sm:grid-cols-3 gap-4">

    <div class="md:col-span-2">
      <%= form.label :name, class:'required' %>
      <%= form.text_field :name, class: "form-input", placeholder: t('activerecord.placeholders.app/status.name') %>
    </div>

    <div class=" group mb-2">
      <%= form.label :active, class:'pointer-events-none' %>
      <%= form.check_box :active, class: "hidden peer" %>
      <%= form.label :active, class:'form-checkbox w-full  dark:bg-gray-900
      group-hover:bg-gray-100        group-hover:peer-checked:bg-blue-700  
      dark:group-hover:bg-gray-950   dark:group-hover:peer-checked:bg-blue-700' do %>
      <% end %>

      <div class="text-base peer-text hidden peer-checked:block "> <%= icon('fa-solid','check')%> <%= t('activerecord.options.app/status_negotiation.active.true')%></div>
      <div class="text-base peer-text block peer-checked:hidden "> <%= icon('fa-solid','xmark')%> <%= t('activerecord.options.app/status_negotiation.active.false')%></div>
    </div>

    <div class="" data-controller="reveal" data-reveal-hidden-class="hidden">

      <%= form.label :icon, class:'inline-flex items-center gap-1 relative' do %>

        <%= form.label :icon %>

        <button data-action="click->reveal#toggle " type="button" class="btn">
          <%= icon('fa-solid', 'circle-info', class:'fa-xs hover:text-blue-600') %>
        </button>

        <div data-reveal-target="item" class="py-1 px-2 bg-gray-100 dark:bg-gray-900 rounded-md absolute left-14 text-xs hidden w-max" id="file_input_help">
          <%= link_to "https://fontawesome.com/search?o=r&m=free", class:'hover:text-blue-600', target:'_blank' do %>
            <%= icon('fa-solid', 'external-link-alt', class:'fa-xs') %>
            Font Awesome Icons
          </div>
        <%end%>
      <%end%>
      <%= form.text_field :icon, class: "form-input", placeholder: t('activerecord.placeholders.app/status.icon') %>
    </div>

    <div class="">
      <%= form.label :style %>
      <%= form.collection_select :style, @styles, :first, :last, {}, {class: "form-input"} %>
    </div>

    <div class="">
      <%= form.label :color %>
      <%= form.select :color, [], {selected: 'amber'}, {class: "form-input"} do %>

        <option class="text-black dark:text-white" value="default" <%= 'selected' if @app_status_negotiation.color == 'default'  %>  >
          <%= t("activerecord.options.general.COLORS.default") %>
        </option>
        <option class="text-red-600 " value="red" <%= 'selected' if @app_status_negotiation.color == 'red'  %> >
          <%= t("activerecord.options.general.COLORS.red") %>
        </option>
        <option class="text-amber-600" value="amber" <%= 'selected' if @app_status_negotiation.color == 'amber'  %> >
          <%= t("activerecord.options.general.COLORS.amber")  %>
        </option>
        <option class="text-orange-600" value="orange" <%= 'selected' if @app_status_negotiation.color == 'orange'  %> >
          <%= t("activerecord.options.general.COLORS.orange") %>
        </option>
        <option class="text-yellow-600" value="yellow" <%= 'selected' if @app_status_negotiation.color == 'yellow'  %> >
          <%= t("activerecord.options.general.COLORS.yellow") %>
        </option>
        <option class="text-lime-600" value="lime" <%= 'selected' if @app_status_negotiation.color == 'lime'  %> >
          <%= t("activerecord.options.general.COLORS.lime") %>
        </option>
        <option class="text-green-600" value="green" <%= 'selected' if @app_status_negotiation.color == 'green'  %> >
          <%= t("activerecord.options.general.COLORS.green") %>
        </option>
        <option class="text-emerald-600" value="emerald" <%= 'selected' if @app_status_negotiation.color == 'emerald'  %> >
          <%= t("activerecord.options.general.COLORS.emerald") %>
        </option>
        <option class="text-teal-600" value="teal" <%= 'selected' if @app_status_negotiation.color == 'teal'  %> >
          <%= t("activerecord.options.general.COLORS.teal") %>
        </option>
        <option class="text-cyan-600" value="cyan" <%= 'selected' if @app_status_negotiation.color == 'cyan'  %> >
          <%= t("activerecord.options.general.COLORS.cyan") %>
        </option>
        <option class="text-sky-600" value="sky" <%= 'selected' if @app_status_negotiation.color == 'sky'  %> >
          <%= t("activerecord.options.general.COLORS.sky") %>
        </option>
        <option class="text-blue-600" value="blue" <%= 'selected' if @app_status_negotiation.color == 'blue'  %> >
          <%= t("activerecord.options.general.COLORS.blue") %>
        </option>
        <option class="text-indigo-600" value="indigo" <%= 'selected' if @app_status_negotiation.color == 'indigo'  %> >
          <%= t("activerecord.options.general.COLORS.indigo") %>
        </option>
        <option class="text-violet-600" value="violet" <%= 'selected' if @app_status_negotiation.color == 'violet'  %> >
          <%= t("activerecord.options.general.COLORS.violet") %>
        </option>
        <option class="text-purple-600" value="purple" <%= 'selected' if @app_status_negotiation.color == 'purple'  %> >
          <%= t("activerecord.options.general.COLORS.purple") %>
        </option>
        <option class="text-fuchsia-600" value="fuchsia" <%= 'selected' if @app_status_negotiation.color == 'fuchsia'  %> >
          <%= t("activerecord.options.general.COLORS.fuchsia") %>
        </option>
        <option class="text-pink-600" value="pink" <%= 'selected' if @app_status_negotiation.color == 'pink'  %> >
          <%= t("activerecord.options.general.COLORS.pink") %>
        </option>
        <option class="text-rose-600" value="rose" <%= 'selected' if @app_status_negotiation.color == 'rose'  %> >
          <%= t("activerecord.options.general.COLORS.rose") %>
        </option>

      <%end%>
    </div>

  </div>

  <div class="mt-4 inline-flex w-full justify-end">
    <%= form.submit class: "btn-primary" %>
  </div>

<% end %>

app/views/app/status_negotiations/_sidebar.html.erb
<div class="" data-controller='search reveal' data-reveal-hidden-class="hidden">
  <div class="detail-input text-xs text-center h-8 -mb-1" id="pagy_info">
   <%== pagy_info(@pagy, item_name: App::StatusNegotiation.model_name.human(count: @pagy.items)) %>
  </div>
  
  <%= form_with(url: search_app_status_negotiations_path, method: :get,  class:'space-y-1') do |form| %>

    <%# SEACH INPUT %>
    <div class="relative" data-action='mouseenter->reveal#toggle mouseleave->reveal#toggle '>
      <div class="search-input-icon dark:hover:bg-blue-600" data-action="click->search#submit"><%= icon('fa-solid','search', class:'fa-sm ') %>  </div>
      <%= form.text_field :query, value:params[:query], class:'search-input text-sm', placeholder: t('views.app.general.search'), data: {action: 'keydown.enter->search#submit'} %>
    </div>
    <div class="hidden  detail-input text-xs h-8 " data-reveal-target="item">
      <p class="text-center">
        <%= %i[ name ].map{|attr| App::StatusNegotiation.human_attribute_name(attr)}.join(" | ")  %>
      </p>
    </div>
    <%# END OF SEARCH INPUT%>

    <%# STATUS INPUT %>

    <%= form.label "status_all", class:'detail-input cursor-pointer mt-0' do %>
      <%= form.radio_button :status, 'all', class:'form-radio-simple mr-1', id:"status_all", checked: (true), data: {action: 'change->search#submit'} %>
      <span class="text-sm"><%= t('activerecord.options.app/company.active.all') %></span>
    <% end %>

    <%= form.label "status_active", class:'detail-input cursor-pointer mt-0' do %>
      <%= form.radio_button :status, 'active', class:'form-radio-simple mr-1', id:"status_active", checked: params[:status] == 'active', data: {action: 'change->search#submit'} %>
      <span class="text-sm"><%= t('activerecord.options.app/company.active.true') %></span>
    <% end %>

    <%= form.label "status_not_active", class:'detail-input cursor-pointer mt-0' do %>
      <%= form.radio_button :status, 'not_active', class:'form-radio-simple mr-1', id:"status_not_active", checked: params[:status] == 'not_active', data: {action: 'change->search#submit'} %>
      <span class="text-sm"><%= t('activerecord.options.app/company.active.false') %></span>
    <% end %>

    <%# END OF STATUS %>

  <% end %>

</div>

app/views/app/status_negotiations/_status_negotiation.html.erb
<div id="<%= dom_id status_negotiation %>"  data-aos='fade' class='card group' data-controller="reveal" data-reveal-hidden-class="grid">

  <div class="card-header">

    <div class="card-header-info my-auto">
      <p class="overflow-scroll scrollbar-hide text-<%=status_negotiation.color%>-600 dark:text-<%=status_negotiation.color%>-600">
        <%= link_to app_status_negotiation_path(status_negotiation), class:'card-header-title' do %>
          <%= icon(status_negotiation.style, status_negotiation.icon)%> <%= status_negotiation.name %>
        <%end%>
      </p>

    </div>

    <%= button_tag class:'card-header-btn',  data: { action:"click->reveal#toggle" } do %>
      <%= icon('fa-solid','bars', class:'fa-sm')%>
    <%end%>

  </div>

  <div data-reveal-target="item" class="card-popover w-24" data-action="mouseleave->reveal#show">

    <%= link_to edit_app_status_negotiation_path(status_negotiation), class:'card-popover-btn-primary' do %>
      <%= icon('fa-solid', 'pen-to-square', class:'btn-icon') %>
      <p class=""> <%= t('views.app.general.edit')%></p>
    <%end%>

  </div>

</div>

app/views/app/status_negotiations/_status_negotiations.html.erb
<div class="default-grid">
  <%= render @app_status_negotiations %>
</div>

app/views/app/status_negotiations/edit.html.erb
<% content_for :ctas_secondary do %>
  <%= link_to app_status_negotiations_path, class: "btn-secondary-gray flex-none" do %>
    <%= icon('fa-solid','arrow-left', class:'-mx-1')%>
  <%end%>

  <%= link_to app_status_negotiation_path(@app_status_negotiation), class: "btn-secondary flex-none" do %>
    <%= icon('fa-solid','arrow-up-right-from-square', class:'-mx-1')%>
  <%end%>
<% end %>

<% provide :head_title, "#{t('views.app.general.editing')} #{App::StatusNegotiation.model_name.human}" %>
<% provide :page_title, "#{t('views.app.general.editing')} #{App::StatusNegotiation.model_name.human}" %>
<% provide :entry_id, "#{@app_status_negotiation.id}" %>

<% content_for :page_content do %>
  <%= render "form", app_status_negotiation: @app_status_negotiation %>
<%end%>

app/views/app/status_negotiations/index.html.erb
<% content_for :ctas_primary do %>
 
  <%= link_to new_app_status_negotiation_path, class: "btn-primary flex-none" do %>
    <%= icon('fa-solid','plus',class:'btn-icon') %>
    <%= App::StatusNegotiation.model_name.human %>
  <% end %>
<% end %>

<% content_for :ctas_secondary do %>
  <%= link_to app_settings_path, class: "btn-secondary-gray flex-none" do %>
    <%= icon('fa-solid','arrow-left', class:'-mx-1')%>
  <%end%>
<%end%>

<% provide :head_title, App::StatusNegotiation.model_name.human(count:2) %>
<% provide :page_title, App::StatusNegotiation.model_name.human(count:2) %>
<% provide :sidebar, render(partial: 'app/status_negotiations/sidebar') %>

<% content_for :page_content do %>

  <%= render partial: 'status_negotiations' %>
<%end%>

app/views/app/status_negotiations/new.html.erb
<% content_for :ctas_secondary do %>
  <%= link_to app_status_negotiations_path, class: "btn-secondary-gray flex-none" do %>
    <%= icon('fa-solid','arrow-left', class:'-mx-1')%>
  <%end%>
<% end %>

<% provide :page_title, "#{t('views.app.general.new')} #{App::StatusNegotiation.model_name.human} (#{App::Negotiation.model_name.human})" %>

<% content_for :page_content do %>
  <%= render "form", app_status_negotiation: @app_status_negotiation %>
<%end%>

app/views/app/status_negotiations/show.html.erb
<% content_for :ctas_secondary do %>
  <%= link_to app_status_negotiations_path, class: "btn-secondary-gray flex-none" do %>
    <%= icon('fa-solid','arrow-left', class:'-mx-1')%>
  <%end%>

  <%= link_to edit_app_status_negotiation_path(@app_status_negotiation), class: "btn-secondary flex-none" do %>
    <%= icon('fa-solid','pen-to-square', class:'-mx-1')%>
  <%end%>

  <%= button_to app_status_negotiation_path(@app_status_negotiation), method: :delete, data: { turbo: false },onclick: "return confirm('#{t('views.app.general.delete_confirm')}')", class: "btn-delete flex-none" do %>
    <%= icon('fa-solid','trash-can', class:'-mx-1')%>
  <%end  unless @app_status_negotiation.has_dependency? %>
<% end %>

<% content_for :ctas_primary do %>

  <%= link_to search_app_negotiations_path(status_ids: [@app_status_negotiation.id]), class: "btn-primary flex-none" do %>
    <%= icon('fa-solid','table-columns',class:'btn-icon') %>
    <%= App::Negotiation.model_name.human(count:2) %>
  <% end %>

<% end %>


<% provide :head_title, "#{t('views.app.general.showing')} #{App::StatusNegotiation.model_name.human} " %>
<% provide :page_title, "#{t('views.app.general.showing')} #{App::StatusNegotiation.model_name.human} " %>
<% provide :entry_id, "#{@app_status_negotiation.id}" %>

<% content_for :page_content do %>
  <%= render "detail", app_status_negotiation: @app_status_negotiation %>
<%end%>